### PR TITLE
Fixes #1 -- ngc errors cause the gulp-ngc plugin fail

### LINKED ISSUE #1: The plugin neglects compilation errors
When the `@angular/compiler` fails to compile, the `gulp-ngc` plugin swallows the errors and returns exit code 0.
The PluginError must be thrown.

### PR DESCRIPTION
**Pull request by milichev**
-- ngc errors cause the gulp-ngc plugin fail with non-zero exit code;
-- added .gitignore;
-- cleared rollup build output

### CODE REVIEW

File: src/index.js [hunk 1]
```diff
@@ -10,11 +11,19 @@ export default (configPath) => {
...
-            ngc(args).then(() => {
-                callback(null, file); 
-            }); 
+            ngc(args)
+                .then((code) => {
+                    let err = code === 0
+                        ? null
+                        : new gutil.PluginError(
+                            'gulp-ngc',
+                            `${gutil.colors.red('Compilation error.')}\nSee details in the ngc output`,
```
Comment (jolly-roger) [inline src/index.js:23]: In case of using string templates, please, plug in Babel into rollup. Thanks.

Comment (jolly-roger) [reply src/index.js:23]: Don't mind, node supported them (string templates) started from v4.0.0.

**Review by jolly-roger — APPROVED** [review]
